### ISSUE TITLE
Generate Trie (n-Gram) structure from OWL 

### ISSUE THREAD

**Issue by craigtrim** [craigtrim/askowl#8]
These are the files from that have this file name pattern: `*_trie.py`

**Comment by craigtrim** [comment]
The `owl2py.yml` config looks like this
```yaml
- classname: <Class>Trie
  filename: <file>_trie
  transformers:
    - lowercase
    - trie
  queries:
    - trie.sparql
```
