### ISSUE TITLE
Generate NER Transform Function

### ISSUE THREAD

**Issue by craigtrim** [craigtrim/askowl#9]
There are value-add components for dealing with OWL relationships.

I have to decide if that's something I want to add here, or if this should be kept as a generic microservice.

**Comment by craigtrim** [comment]
This lookup transform could be useful
```yaml
  - classname: <Class>Lookup
    filename: <file>_lookup
    transformers:
      - lowercase
      - lookup
    queries:
      - lookup.sparql
    files:
      - <file>.txt
```

Simply as a way of extracting n-grams from the OWL model.
